builds:
  - env:
      - CGO_ENABLED=0
    ldflags: --ldflags "-X github.com/yusukebe/gh-markdown-preview/cmd.Version=$(git describe --tag --abbrev=0)"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format: binary
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
